In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("Air_Quality_Prediction.csv")
df.head()

Date    Country                          Status  AQI Value
0  2022-07-21    Albania                            Good         14
1  2022-07-21    Algeria                        Moderate         65
2  2022-07-21    Andorra                        Moderate         55
3  2022-07-21     Angola  Unhealthy for Sensitive Groups        113
4  2022-07-21  Argentina                        Moderate         63

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17877 entries, 0 to 17876
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Date       17877 non-null  object
 1   Country    17877 non-null  object
 2   Status     17877 non-null  object
 3   AQI Value  17877 non-null  int64 
dtypes: int64(1), object(3)
memory usage: 558.8+ KB


In [ ]:
df.describe()

AQI Value
count  17877.000000
mean      63.523578
std       50.128197
min        1.000000
25%       29.000000
50%       53.000000
75%       83.000000
max      963.000000

In [ ]:
df.drop(columns=["Date"],inplace=True)

In [ ]:
df.tail()

Country  \
17872  United Kingdom of Great Britain and Northern I...   
17873                           United States of America   
17874                                         Uzbekistan   
17875                                            Vatican   
17876                                            Vietnam   

                               Status  AQI Value  
17872  Unhealthy for Sensitive Groups        139  
17873                        Moderate         98  
17874                            Good         46  
17875                        Moderate         65  
17876                        Moderate         94

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for i in ["Status","Country"]:
  df[i]=label_encoder.fit_transform(df[i])


In [ ]:
df.head()

Country  Status  AQI Value
0        0       0         14
1        1       2         65
2        2       2         55
3        3       4        113
4        4       2         63

In [ ]:
x = df.drop(columns=["AQI Value"])
y = df["AQI Value"]

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=57)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain, ytrain)

LogisticRegression()

In [ ]:
ypred = model.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(ytest, ypred)
conf_matrix = confusion_matrix(ytest, ypred)
class_report = classification_report(ytest, ypred)

# Print results
print("Model Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Model Accuracy: 0.06795302013422819
Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00        23
           2       0.00      0.00      0.00        15
           3       0.00      0.00      0.00        13
           4       0.00      0.00      0.00         9
           5       0.00      0.00      0.00        14
           6       0.00      0.00      0.00         7
           7       0.00      0.00      0.00        16
           8       0.00      0.00      0.00        24
           9       0.00      0.00      0.00        16
          10       0.00      0.00      0.00        40
          11       0.00      0.00      0.00        33
          12       0.00      0.00      0.00        23
          13       0.00      0.00      0.00        35
          14       0.00      0.00      0.00 

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
